name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write  # Allows pushing packages to GHCR
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Git identity
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"

    - name: Read the current version
      id: read_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Increment the version
      id: increment_version
      run: |
        IFS='.' read -r major minor patch <<< "${{ env.VERSION }}"
        new_patch=$((patch + 1))
        NEW_VERSION="$major.$minor.$new_patch"
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Save the new version
      run: echo "${{ env.NEW_VERSION }}" > version.txt

    - name: Commit version change
      run: |
        git add version.txt
        git commit -m "Increment version to ${{ env.NEW_VERSION }}"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/haghdk/budgetapp.git
        git push

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build -f backend/Dockerfile -t ghcr.io/${{ github.repository_owner }}/budgetapp-backend:${{ env.NEW_VERSION }} ./backend

    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/budgetapp-backend:${{ env.NEW_VERSION }}
