name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Fetch all tags
      run: git fetch --tags

    - name: Get the latest tag
      id: get_tag
      run: echo "TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

    - name: Calculate the new version
      id: calculate_version
      run: |
        if [ -z "${{ env.TAG }}" ]; then
          NEW_VERSION="1.0.0"
        else
          IFS='.' read -r major minor patch <<< "${{ env.TAG }}"
          new_patch=$((patch + 1))
          NEW_VERSION="$major.$minor.$new_patch"
        fi
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Create a new tag
      run: |
        git tag -a "${{ env.NEW_VERSION }}" -m "Release ${{ env.NEW_VERSION }}"
        git push origin "${{ env.NEW_VERSION }}"

    - name: Build the Docker image
      run: docker build -f backend/Dockerfile -t budgetapp-backend:${{ env.NEW_VERSION }} ./backend
